# coding: utf-8

# flake8: noqa

"""
    Radarr

    Radarr API docs

    The version of the OpenAPI document: v5.27.5.10198
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.2.1" # x-release-please-version

# Define package exports
__all__ = [
    "AlternativeTitleApi",
    "ApiInfoApi",
    "AuthenticationApi",
    "AutoTaggingApi",
    "BackupApi",
    "BlocklistApi",
    "CalendarApi",
    "CalendarFeedApi",
    "CollectionApi",
    "CommandApi",
    "CreditApi",
    "CustomFilterApi",
    "CustomFormatApi",
    "CutoffApi",
    "DelayProfileApi",
    "DiskSpaceApi",
    "DownloadClientApi",
    "DownloadClientConfigApi",
    "ExtraFileApi",
    "FileSystemApi",
    "HealthApi",
    "HistoryApi",
    "HostConfigApi",
    "ImportListApi",
    "ImportListConfigApi",
    "ImportListExclusionApi",
    "ImportListMoviesApi",
    "IndexerApi",
    "IndexerConfigApi",
    "IndexerFlagApi",
    "LanguageApi",
    "LocalizationApi",
    "LogApi",
    "LogFileApi",
    "ManualImportApi",
    "MediaCoverApi",
    "MediaManagementConfigApi",
    "MetadataApi",
    "MetadataConfigApi",
    "MissingApi",
    "MovieApi",
    "MovieEditorApi",
    "MovieFileApi",
    "MovieFolderApi",
    "MovieImportApi",
    "MovieLookupApi",
    "NamingConfigApi",
    "NotificationApi",
    "ParseApi",
    "PingApi",
    "QualityDefinitionApi",
    "QualityProfileApi",
    "QualityProfileSchemaApi",
    "QueueApi",
    "QueueActionApi",
    "QueueDetailsApi",
    "QueueStatusApi",
    "ReleaseApi",
    "ReleaseProfileApi",
    "ReleasePushApi",
    "RemotePathMappingApi",
    "RenameMovieApi",
    "RootFolderApi",
    "StaticResourceApi",
    "SystemApi",
    "TagApi",
    "TagDetailsApi",
    "TaskApi",
    "UiConfigApi",
    "UpdateApi",
    "UpdateLogFileApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddMovieMethod",
    "AddMovieOptions",
    "AlternativeTitleResource",
    "ApiInfoResource",
    "ApplyTags",
    "AuthenticationRequiredType",
    "AuthenticationType",
    "AutoTaggingResource",
    "AutoTaggingSpecificationSchema",
    "BackupResource",
    "BackupType",
    "BlocklistBulkResource",
    "BlocklistResource",
    "BlocklistResourcePagingResource",
    "CalendarReleaseType",
    "CertificateValidationType",
    "CollectionMovieResource",
    "CollectionResource",
    "CollectionUpdateResource",
    "ColonReplacementFormat",
    "Command",
    "CommandPriority",
    "CommandResource",
    "CommandResult",
    "CommandStatus",
    "CommandTrigger",
    "ContractField",
    "CreditResource",
    "CreditType",
    "CustomFilterResource",
    "CustomFormatBulkResource",
    "CustomFormatResource",
    "CustomFormatSpecificationSchema",
    "DatabaseType",
    "DelayProfileResource",
    "DiskSpaceResource",
    "DownloadClientBulkResource",
    "DownloadClientConfigResource",
    "DownloadClientResource",
    "DownloadProtocol",
    "ExtraFileResource",
    "ExtraFileType",
    "FileDateType",
    "HealthCheckResult",
    "HealthResource",
    "HistoryResource",
    "HistoryResourcePagingResource",
    "HostConfigResource",
    "ImportListBulkResource",
    "ImportListConfigResource",
    "ImportListExclusionBulkResource",
    "ImportListExclusionResource",
    "ImportListExclusionResourcePagingResource",
    "ImportListResource",
    "ImportListType",
    "ImportRejectionResource",
    "IndexerBulkResource",
    "IndexerConfigResource",
    "IndexerFlagResource",
    "IndexerResource",
    "Language",
    "LanguageResource",
    "LocalizationLanguageResource",
    "LogFileResource",
    "LogResource",
    "LogResourcePagingResource",
    "ManualImportReprocessResource",
    "ManualImportResource",
    "MediaCover",
    "MediaCoverTypes",
    "MediaInfoResource",
    "MediaManagementConfigResource",
    "MetadataConfigResource",
    "MetadataResource",
    "Modifier",
    "MonitorTypes",
    "MovieCollectionResource",
    "MovieEditorResource",
    "MovieFileListResource",
    "MovieFileResource",
    "MovieHistoryEventType",
    "MovieResource",
    "MovieResourcePagingResource",
    "MovieRuntimeFormatType",
    "MovieStatisticsResource",
    "MovieStatusType",
    "NamingConfigResource",
    "NotificationResource",
    "ParseResource",
    "ParsedMovieInfo",
    "PingResource",
    "PrivacyLevel",
    "ProfileFormatItemResource",
    "ProperDownloadTypes",
    "ProviderMessage",
    "ProviderMessageType",
    "ProxyType",
    "Quality",
    "QualityDefinitionLimitsResource",
    "QualityDefinitionResource",
    "QualityModel",
    "QualityProfileQualityItemResource",
    "QualityProfileResource",
    "QualitySource",
    "QueueBulkResource",
    "QueueResource",
    "QueueResourcePagingResource",
    "QueueStatus",
    "QueueStatusResource",
    "RatingChild",
    "RatingType",
    "Ratings",
    "RejectionType",
    "ReleaseProfileResource",
    "ReleaseResource",
    "RemotePathMappingResource",
    "RenameMovieResource",
    "RescanAfterRefreshType",
    "Revision",
    "RootFolderResource",
    "RuntimeMode",
    "SelectOption",
    "SortDirection",
    "SourceType",
    "SystemResource",
    "TMDbCountryCode",
    "TagDetailsResource",
    "TagResource",
    "TaskResource",
    "TrackedDownloadState",
    "TrackedDownloadStatus",
    "TrackedDownloadStatusMessage",
    "UiConfigResource",
    "UnmappedFolder",
    "UpdateChanges",
    "UpdateMechanism",
    "UpdateResource",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from radarr.api.alternative_title_api import AlternativeTitleApi as AlternativeTitleApi
    from radarr.api.api_info_api import ApiInfoApi as ApiInfoApi
    from radarr.api.authentication_api import AuthenticationApi as AuthenticationApi
    from radarr.api.auto_tagging_api import AutoTaggingApi as AutoTaggingApi
    from radarr.api.backup_api import BackupApi as BackupApi
    from radarr.api.blocklist_api import BlocklistApi as BlocklistApi
    from radarr.api.calendar_api import CalendarApi as CalendarApi
    from radarr.api.calendar_feed_api import CalendarFeedApi as CalendarFeedApi
    from radarr.api.collection_api import CollectionApi as CollectionApi
    from radarr.api.command_api import CommandApi as CommandApi
    from radarr.api.credit_api import CreditApi as CreditApi
    from radarr.api.custom_filter_api import CustomFilterApi as CustomFilterApi
    from radarr.api.custom_format_api import CustomFormatApi as CustomFormatApi
    from radarr.api.cutoff_api import CutoffApi as CutoffApi
    from radarr.api.delay_profile_api import DelayProfileApi as DelayProfileApi
    from radarr.api.disk_space_api import DiskSpaceApi as DiskSpaceApi
    from radarr.api.download_client_api import DownloadClientApi as DownloadClientApi
    from radarr.api.download_client_config_api import DownloadClientConfigApi as DownloadClientConfigApi
    from radarr.api.extra_file_api import ExtraFileApi as ExtraFileApi
    from radarr.api.file_system_api import FileSystemApi as FileSystemApi
    from radarr.api.health_api import HealthApi as HealthApi
    from radarr.api.history_api import HistoryApi as HistoryApi
    from radarr.api.host_config_api import HostConfigApi as HostConfigApi
    from radarr.api.import_list_api import ImportListApi as ImportListApi
    from radarr.api.import_list_config_api import ImportListConfigApi as ImportListConfigApi
    from radarr.api.import_list_exclusion_api import ImportListExclusionApi as ImportListExclusionApi
    from radarr.api.import_list_movies_api import ImportListMoviesApi as ImportListMoviesApi
    from radarr.api.indexer_api import IndexerApi as IndexerApi
    from radarr.api.indexer_config_api import IndexerConfigApi as IndexerConfigApi
    from radarr.api.indexer_flag_api import IndexerFlagApi as IndexerFlagApi
    from radarr.api.language_api import LanguageApi as LanguageApi
    from radarr.api.localization_api import LocalizationApi as LocalizationApi
    from radarr.api.log_api import LogApi as LogApi
    from radarr.api.log_file_api import LogFileApi as LogFileApi
    from radarr.api.manual_import_api import ManualImportApi as ManualImportApi
    from radarr.api.media_cover_api import MediaCoverApi as MediaCoverApi
    from radarr.api.media_management_config_api import MediaManagementConfigApi as MediaManagementConfigApi
    from radarr.api.metadata_api import MetadataApi as MetadataApi
    from radarr.api.metadata_config_api import MetadataConfigApi as MetadataConfigApi
    from radarr.api.missing_api import MissingApi as MissingApi
    from radarr.api.movie_api import MovieApi as MovieApi
    from radarr.api.movie_editor_api import MovieEditorApi as MovieEditorApi
    from radarr.api.movie_file_api import MovieFileApi as MovieFileApi
    from radarr.api.movie_folder_api import MovieFolderApi as MovieFolderApi
    from radarr.api.movie_import_api import MovieImportApi as MovieImportApi
    from radarr.api.movie_lookup_api import MovieLookupApi as MovieLookupApi
    from radarr.api.naming_config_api import NamingConfigApi as NamingConfigApi
    from radarr.api.notification_api import NotificationApi as NotificationApi
    from radarr.api.parse_api import ParseApi as ParseApi
    from radarr.api.ping_api import PingApi as PingApi
    from radarr.api.quality_definition_api import QualityDefinitionApi as QualityDefinitionApi
    from radarr.api.quality_profile_api import QualityProfileApi as QualityProfileApi
    from radarr.api.quality_profile_schema_api import QualityProfileSchemaApi as QualityProfileSchemaApi
    from radarr.api.queue_api import QueueApi as QueueApi
    from radarr.api.queue_action_api import QueueActionApi as QueueActionApi
    from radarr.api.queue_details_api import QueueDetailsApi as QueueDetailsApi
    from radarr.api.queue_status_api import QueueStatusApi as QueueStatusApi
    from radarr.api.release_api import ReleaseApi as ReleaseApi
    from radarr.api.release_profile_api import ReleaseProfileApi as ReleaseProfileApi
    from radarr.api.release_push_api import ReleasePushApi as ReleasePushApi
    from radarr.api.remote_path_mapping_api import RemotePathMappingApi as RemotePathMappingApi
    from radarr.api.rename_movie_api import RenameMovieApi as RenameMovieApi
    from radarr.api.root_folder_api import RootFolderApi as RootFolderApi
    from radarr.api.static_resource_api import StaticResourceApi as StaticResourceApi
    from radarr.api.system_api import SystemApi as SystemApi
    from radarr.api.tag_api import TagApi as TagApi
    from radarr.api.tag_details_api import TagDetailsApi as TagDetailsApi
    from radarr.api.task_api import TaskApi as TaskApi
    from radarr.api.ui_config_api import UiConfigApi as UiConfigApi
    from radarr.api.update_api import UpdateApi as UpdateApi
    from radarr.api.update_log_file_api import UpdateLogFileApi as UpdateLogFileApi
    
    # import ApiClient
    from radarr.api_response import ApiResponse as ApiResponse
    from radarr.api_client import ApiClient as ApiClient
    from radarr.configuration import Configuration as Configuration
    from radarr.exceptions import OpenApiException as OpenApiException
    from radarr.exceptions import ApiTypeError as ApiTypeError
    from radarr.exceptions import ApiValueError as ApiValueError
    from radarr.exceptions import ApiKeyError as ApiKeyError
    from radarr.exceptions import ApiAttributeError as ApiAttributeError
    from radarr.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from radarr.models.add_movie_method import AddMovieMethod as AddMovieMethod
    from radarr.models.add_movie_options import AddMovieOptions as AddMovieOptions
    from radarr.models.alternative_title_resource import AlternativeTitleResource as AlternativeTitleResource
    from radarr.models.api_info_resource import ApiInfoResource as ApiInfoResource
    from radarr.models.apply_tags import ApplyTags as ApplyTags
    from radarr.models.authentication_required_type import AuthenticationRequiredType as AuthenticationRequiredType
    from radarr.models.authentication_type import AuthenticationType as AuthenticationType
    from radarr.models.auto_tagging_resource import AutoTaggingResource as AutoTaggingResource
    from radarr.models.auto_tagging_specification_schema import AutoTaggingSpecificationSchema as AutoTaggingSpecificationSchema
    from radarr.models.backup_resource import BackupResource as BackupResource
    from radarr.models.backup_type import BackupType as BackupType
    from radarr.models.blocklist_bulk_resource import BlocklistBulkResource as BlocklistBulkResource
    from radarr.models.blocklist_resource import BlocklistResource as BlocklistResource
    from radarr.models.blocklist_resource_paging_resource import BlocklistResourcePagingResource as BlocklistResourcePagingResource
    from radarr.models.calendar_release_type import CalendarReleaseType as CalendarReleaseType
    from radarr.models.certificate_validation_type import CertificateValidationType as CertificateValidationType
    from radarr.models.collection_movie_resource import CollectionMovieResource as CollectionMovieResource
    from radarr.models.collection_resource import CollectionResource as CollectionResource
    from radarr.models.collection_update_resource import CollectionUpdateResource as CollectionUpdateResource
    from radarr.models.colon_replacement_format import ColonReplacementFormat as ColonReplacementFormat
    from radarr.models.command import Command as Command
    from radarr.models.command_priority import CommandPriority as CommandPriority
    from radarr.models.command_resource import CommandResource as CommandResource
    from radarr.models.command_result import CommandResult as CommandResult
    from radarr.models.command_status import CommandStatus as CommandStatus
    from radarr.models.command_trigger import CommandTrigger as CommandTrigger
    from radarr.models.contract_field import ContractField as ContractField
    from radarr.models.credit_resource import CreditResource as CreditResource
    from radarr.models.credit_type import CreditType as CreditType
    from radarr.models.custom_filter_resource import CustomFilterResource as CustomFilterResource
    from radarr.models.custom_format_bulk_resource import CustomFormatBulkResource as CustomFormatBulkResource
    from radarr.models.custom_format_resource import CustomFormatResource as CustomFormatResource
    from radarr.models.custom_format_specification_schema import CustomFormatSpecificationSchema as CustomFormatSpecificationSchema
    from radarr.models.database_type import DatabaseType as DatabaseType
    from radarr.models.delay_profile_resource import DelayProfileResource as DelayProfileResource
    from radarr.models.disk_space_resource import DiskSpaceResource as DiskSpaceResource
    from radarr.models.download_client_bulk_resource import DownloadClientBulkResource as DownloadClientBulkResource
    from radarr.models.download_client_config_resource import DownloadClientConfigResource as DownloadClientConfigResource
    from radarr.models.download_client_resource import DownloadClientResource as DownloadClientResource
    from radarr.models.download_protocol import DownloadProtocol as DownloadProtocol
    from radarr.models.extra_file_resource import ExtraFileResource as ExtraFileResource
    from radarr.models.extra_file_type import ExtraFileType as ExtraFileType
    from radarr.models.file_date_type import FileDateType as FileDateType
    from radarr.models.health_check_result import HealthCheckResult as HealthCheckResult
    from radarr.models.health_resource import HealthResource as HealthResource
    from radarr.models.history_resource import HistoryResource as HistoryResource
    from radarr.models.history_resource_paging_resource import HistoryResourcePagingResource as HistoryResourcePagingResource
    from radarr.models.host_config_resource import HostConfigResource as HostConfigResource
    from radarr.models.import_list_bulk_resource import ImportListBulkResource as ImportListBulkResource
    from radarr.models.import_list_config_resource import ImportListConfigResource as ImportListConfigResource
    from radarr.models.import_list_exclusion_bulk_resource import ImportListExclusionBulkResource as ImportListExclusionBulkResource
    from radarr.models.import_list_exclusion_resource import ImportListExclusionResource as ImportListExclusionResource
    from radarr.models.import_list_exclusion_resource_paging_resource import ImportListExclusionResourcePagingResource as ImportListExclusionResourcePagingResource
    from radarr.models.import_list_resource import ImportListResource as ImportListResource
    from radarr.models.import_list_type import ImportListType as ImportListType
    from radarr.models.import_rejection_resource import ImportRejectionResource as ImportRejectionResource
    from radarr.models.indexer_bulk_resource import IndexerBulkResource as IndexerBulkResource
    from radarr.models.indexer_config_resource import IndexerConfigResource as IndexerConfigResource
    from radarr.models.indexer_flag_resource import IndexerFlagResource as IndexerFlagResource
    from radarr.models.indexer_resource import IndexerResource as IndexerResource
    from radarr.models.language import Language as Language
    from radarr.models.language_resource import LanguageResource as LanguageResource
    from radarr.models.localization_language_resource import LocalizationLanguageResource as LocalizationLanguageResource
    from radarr.models.log_file_resource import LogFileResource as LogFileResource
    from radarr.models.log_resource import LogResource as LogResource
    from radarr.models.log_resource_paging_resource import LogResourcePagingResource as LogResourcePagingResource
    from radarr.models.manual_import_reprocess_resource import ManualImportReprocessResource as ManualImportReprocessResource
    from radarr.models.manual_import_resource import ManualImportResource as ManualImportResource
    from radarr.models.media_cover import MediaCover as MediaCover
    from radarr.models.media_cover_types import MediaCoverTypes as MediaCoverTypes
    from radarr.models.media_info_resource import MediaInfoResource as MediaInfoResource
    from radarr.models.media_management_config_resource import MediaManagementConfigResource as MediaManagementConfigResource
    from radarr.models.metadata_config_resource import MetadataConfigResource as MetadataConfigResource
    from radarr.models.metadata_resource import MetadataResource as MetadataResource
    from radarr.models.modifier import Modifier as Modifier
    from radarr.models.monitor_types import MonitorTypes as MonitorTypes
    from radarr.models.movie_collection_resource import MovieCollectionResource as MovieCollectionResource
    from radarr.models.movie_editor_resource import MovieEditorResource as MovieEditorResource
    from radarr.models.movie_file_list_resource import MovieFileListResource as MovieFileListResource
    from radarr.models.movie_file_resource import MovieFileResource as MovieFileResource
    from radarr.models.movie_history_event_type import MovieHistoryEventType as MovieHistoryEventType
    from radarr.models.movie_resource import MovieResource as MovieResource
    from radarr.models.movie_resource_paging_resource import MovieResourcePagingResource as MovieResourcePagingResource
    from radarr.models.movie_runtime_format_type import MovieRuntimeFormatType as MovieRuntimeFormatType
    from radarr.models.movie_statistics_resource import MovieStatisticsResource as MovieStatisticsResource
    from radarr.models.movie_status_type import MovieStatusType as MovieStatusType
    from radarr.models.naming_config_resource import NamingConfigResource as NamingConfigResource
    from radarr.models.notification_resource import NotificationResource as NotificationResource
    from radarr.models.parse_resource import ParseResource as ParseResource
    from radarr.models.parsed_movie_info import ParsedMovieInfo as ParsedMovieInfo
    from radarr.models.ping_resource import PingResource as PingResource
    from radarr.models.privacy_level import PrivacyLevel as PrivacyLevel
    from radarr.models.profile_format_item_resource import ProfileFormatItemResource as ProfileFormatItemResource
    from radarr.models.proper_download_types import ProperDownloadTypes as ProperDownloadTypes
    from radarr.models.provider_message import ProviderMessage as ProviderMessage
    from radarr.models.provider_message_type import ProviderMessageType as ProviderMessageType
    from radarr.models.proxy_type import ProxyType as ProxyType
    from radarr.models.quality import Quality as Quality
    from radarr.models.quality_definition_limits_resource import QualityDefinitionLimitsResource as QualityDefinitionLimitsResource
    from radarr.models.quality_definition_resource import QualityDefinitionResource as QualityDefinitionResource
    from radarr.models.quality_model import QualityModel as QualityModel
    from radarr.models.quality_profile_quality_item_resource import QualityProfileQualityItemResource as QualityProfileQualityItemResource
    from radarr.models.quality_profile_resource import QualityProfileResource as QualityProfileResource
    from radarr.models.quality_source import QualitySource as QualitySource
    from radarr.models.queue_bulk_resource import QueueBulkResource as QueueBulkResource
    from radarr.models.queue_resource import QueueResource as QueueResource
    from radarr.models.queue_resource_paging_resource import QueueResourcePagingResource as QueueResourcePagingResource
    from radarr.models.queue_status import QueueStatus as QueueStatus
    from radarr.models.queue_status_resource import QueueStatusResource as QueueStatusResource
    from radarr.models.rating_child import RatingChild as RatingChild
    from radarr.models.rating_type import RatingType as RatingType
    from radarr.models.ratings import Ratings as Ratings
    from radarr.models.rejection_type import RejectionType as RejectionType
    from radarr.models.release_profile_resource import ReleaseProfileResource as ReleaseProfileResource
    from radarr.models.release_resource import ReleaseResource as ReleaseResource
    from radarr.models.remote_path_mapping_resource import RemotePathMappingResource as RemotePathMappingResource
    from radarr.models.rename_movie_resource import RenameMovieResource as RenameMovieResource
    from radarr.models.rescan_after_refresh_type import RescanAfterRefreshType as RescanAfterRefreshType
    from radarr.models.revision import Revision as Revision
    from radarr.models.root_folder_resource import RootFolderResource as RootFolderResource
    from radarr.models.runtime_mode import RuntimeMode as RuntimeMode
    from radarr.models.select_option import SelectOption as SelectOption
    from radarr.models.sort_direction import SortDirection as SortDirection
    from radarr.models.source_type import SourceType as SourceType
    from radarr.models.system_resource import SystemResource as SystemResource
    from radarr.models.tmdb_country_code import TMDbCountryCode as TMDbCountryCode
    from radarr.models.tag_details_resource import TagDetailsResource as TagDetailsResource
    from radarr.models.tag_resource import TagResource as TagResource
    from radarr.models.task_resource import TaskResource as TaskResource
    from radarr.models.tracked_download_state import TrackedDownloadState as TrackedDownloadState
    from radarr.models.tracked_download_status import TrackedDownloadStatus as TrackedDownloadStatus
    from radarr.models.tracked_download_status_message import TrackedDownloadStatusMessage as TrackedDownloadStatusMessage
    from radarr.models.ui_config_resource import UiConfigResource as UiConfigResource
    from radarr.models.unmapped_folder import UnmappedFolder as UnmappedFolder
    from radarr.models.update_changes import UpdateChanges as UpdateChanges
    from radarr.models.update_mechanism import UpdateMechanism as UpdateMechanism
    from radarr.models.update_resource import UpdateResource as UpdateResource
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from radarr.api.alternative_title_api import AlternativeTitleApi as AlternativeTitleApi
from radarr.api.api_info_api import ApiInfoApi as ApiInfoApi
from radarr.api.authentication_api import AuthenticationApi as AuthenticationApi
from radarr.api.auto_tagging_api import AutoTaggingApi as AutoTaggingApi
from radarr.api.backup_api import BackupApi as BackupApi
from radarr.api.blocklist_api import BlocklistApi as BlocklistApi
from radarr.api.calendar_api import CalendarApi as CalendarApi
from radarr.api.calendar_feed_api import CalendarFeedApi as CalendarFeedApi
from radarr.api.collection_api import CollectionApi as CollectionApi
from radarr.api.command_api import CommandApi as CommandApi
from radarr.api.credit_api import CreditApi as CreditApi
from radarr.api.custom_filter_api import CustomFilterApi as CustomFilterApi
from radarr.api.custom_format_api import CustomFormatApi as CustomFormatApi
from radarr.api.cutoff_api import CutoffApi as CutoffApi
from radarr.api.delay_profile_api import DelayProfileApi as DelayProfileApi
from radarr.api.disk_space_api import DiskSpaceApi as DiskSpaceApi
from radarr.api.download_client_api import DownloadClientApi as DownloadClientApi
from radarr.api.download_client_config_api import DownloadClientConfigApi as DownloadClientConfigApi
from radarr.api.extra_file_api import ExtraFileApi as ExtraFileApi
from radarr.api.file_system_api import FileSystemApi as FileSystemApi
from radarr.api.health_api import HealthApi as HealthApi
from radarr.api.history_api import HistoryApi as HistoryApi
from radarr.api.host_config_api import HostConfigApi as HostConfigApi
from radarr.api.import_list_api import ImportListApi as ImportListApi
from radarr.api.import_list_config_api import ImportListConfigApi as ImportListConfigApi
from radarr.api.import_list_exclusion_api import ImportListExclusionApi as ImportListExclusionApi
from radarr.api.import_list_movies_api import ImportListMoviesApi as ImportListMoviesApi
from radarr.api.indexer_api import IndexerApi as IndexerApi
from radarr.api.indexer_config_api import IndexerConfigApi as IndexerConfigApi
from radarr.api.indexer_flag_api import IndexerFlagApi as IndexerFlagApi
from radarr.api.language_api import LanguageApi as LanguageApi
from radarr.api.localization_api import LocalizationApi as LocalizationApi
from radarr.api.log_api import LogApi as LogApi
from radarr.api.log_file_api import LogFileApi as LogFileApi
from radarr.api.manual_import_api import ManualImportApi as ManualImportApi
from radarr.api.media_cover_api import MediaCoverApi as MediaCoverApi
from radarr.api.media_management_config_api import MediaManagementConfigApi as MediaManagementConfigApi
from radarr.api.metadata_api import MetadataApi as MetadataApi
from radarr.api.metadata_config_api import MetadataConfigApi as MetadataConfigApi
from radarr.api.missing_api import MissingApi as MissingApi
from radarr.api.movie_api import MovieApi as MovieApi
from radarr.api.movie_editor_api import MovieEditorApi as MovieEditorApi
from radarr.api.movie_file_api import MovieFileApi as MovieFileApi
from radarr.api.movie_folder_api import MovieFolderApi as MovieFolderApi
from radarr.api.movie_import_api import MovieImportApi as MovieImportApi
from radarr.api.movie_lookup_api import MovieLookupApi as MovieLookupApi
from radarr.api.naming_config_api import NamingConfigApi as NamingConfigApi
from radarr.api.notification_api import NotificationApi as NotificationApi
from radarr.api.parse_api import ParseApi as ParseApi
from radarr.api.ping_api import PingApi as PingApi
from radarr.api.quality_definition_api import QualityDefinitionApi as QualityDefinitionApi
from radarr.api.quality_profile_api import QualityProfileApi as QualityProfileApi
from radarr.api.quality_profile_schema_api import QualityProfileSchemaApi as QualityProfileSchemaApi
from radarr.api.queue_api import QueueApi as QueueApi
from radarr.api.queue_action_api import QueueActionApi as QueueActionApi
from radarr.api.queue_details_api import QueueDetailsApi as QueueDetailsApi
from radarr.api.queue_status_api import QueueStatusApi as QueueStatusApi
from radarr.api.release_api import ReleaseApi as ReleaseApi
from radarr.api.release_profile_api import ReleaseProfileApi as ReleaseProfileApi
from radarr.api.release_push_api import ReleasePushApi as ReleasePushApi
from radarr.api.remote_path_mapping_api import RemotePathMappingApi as RemotePathMappingApi
from radarr.api.rename_movie_api import RenameMovieApi as RenameMovieApi
from radarr.api.root_folder_api import RootFolderApi as RootFolderApi
from radarr.api.static_resource_api import StaticResourceApi as StaticResourceApi
from radarr.api.system_api import SystemApi as SystemApi
from radarr.api.tag_api import TagApi as TagApi
from radarr.api.tag_details_api import TagDetailsApi as TagDetailsApi
from radarr.api.task_api import TaskApi as TaskApi
from radarr.api.ui_config_api import UiConfigApi as UiConfigApi
from radarr.api.update_api import UpdateApi as UpdateApi
from radarr.api.update_log_file_api import UpdateLogFileApi as UpdateLogFileApi

# import ApiClient
from radarr.api_response import ApiResponse as ApiResponse
from radarr.api_client import ApiClient as ApiClient
from radarr.configuration import Configuration as Configuration
from radarr.exceptions import OpenApiException as OpenApiException
from radarr.exceptions import ApiTypeError as ApiTypeError
from radarr.exceptions import ApiValueError as ApiValueError
from radarr.exceptions import ApiKeyError as ApiKeyError
from radarr.exceptions import ApiAttributeError as ApiAttributeError
from radarr.exceptions import ApiException as ApiException

# import models into sdk package
from radarr.models.add_movie_method import AddMovieMethod as AddMovieMethod
from radarr.models.add_movie_options import AddMovieOptions as AddMovieOptions
from radarr.models.alternative_title_resource import AlternativeTitleResource as AlternativeTitleResource
from radarr.models.api_info_resource import ApiInfoResource as ApiInfoResource
from radarr.models.apply_tags import ApplyTags as ApplyTags
from radarr.models.authentication_required_type import AuthenticationRequiredType as AuthenticationRequiredType
from radarr.models.authentication_type import AuthenticationType as AuthenticationType
from radarr.models.auto_tagging_resource import AutoTaggingResource as AutoTaggingResource
from radarr.models.auto_tagging_specification_schema import AutoTaggingSpecificationSchema as AutoTaggingSpecificationSchema
from radarr.models.backup_resource import BackupResource as BackupResource
from radarr.models.backup_type import BackupType as BackupType
from radarr.models.blocklist_bulk_resource import BlocklistBulkResource as BlocklistBulkResource
from radarr.models.blocklist_resource import BlocklistResource as BlocklistResource
from radarr.models.blocklist_resource_paging_resource import BlocklistResourcePagingResource as BlocklistResourcePagingResource
from radarr.models.calendar_release_type import CalendarReleaseType as CalendarReleaseType
from radarr.models.certificate_validation_type import CertificateValidationType as CertificateValidationType
from radarr.models.collection_movie_resource import CollectionMovieResource as CollectionMovieResource
from radarr.models.collection_resource import CollectionResource as CollectionResource
from radarr.models.collection_update_resource import CollectionUpdateResource as CollectionUpdateResource
from radarr.models.colon_replacement_format import ColonReplacementFormat as ColonReplacementFormat
from radarr.models.command import Command as Command
from radarr.models.command_priority import CommandPriority as CommandPriority
from radarr.models.command_resource import CommandResource as CommandResource
from radarr.models.command_result import CommandResult as CommandResult
from radarr.models.command_status import CommandStatus as CommandStatus
from radarr.models.command_trigger import CommandTrigger as CommandTrigger
from radarr.models.contract_field import ContractField as ContractField
from radarr.models.credit_resource import CreditResource as CreditResource
from radarr.models.credit_type import CreditType as CreditType
from radarr.models.custom_filter_resource import CustomFilterResource as CustomFilterResource
from radarr.models.custom_format_bulk_resource import CustomFormatBulkResource as CustomFormatBulkResource
from radarr.models.custom_format_resource import CustomFormatResource as CustomFormatResource
from radarr.models.custom_format_specification_schema import CustomFormatSpecificationSchema as CustomFormatSpecificationSchema
from radarr.models.database_type import DatabaseType as DatabaseType
from radarr.models.delay_profile_resource import DelayProfileResource as DelayProfileResource
from radarr.models.disk_space_resource import DiskSpaceResource as DiskSpaceResource
from radarr.models.download_client_bulk_resource import DownloadClientBulkResource as DownloadClientBulkResource
from radarr.models.download_client_config_resource import DownloadClientConfigResource as DownloadClientConfigResource
from radarr.models.download_client_resource import DownloadClientResource as DownloadClientResource
from radarr.models.download_protocol import DownloadProtocol as DownloadProtocol
from radarr.models.extra_file_resource import ExtraFileResource as ExtraFileResource
from radarr.models.extra_file_type import ExtraFileType as ExtraFileType
from radarr.models.file_date_type import FileDateType as FileDateType
from radarr.models.health_check_result import HealthCheckResult as HealthCheckResult
from radarr.models.health_resource import HealthResource as HealthResource
from radarr.models.history_resource import HistoryResource as HistoryResource
from radarr.models.history_resource_paging_resource import HistoryResourcePagingResource as HistoryResourcePagingResource
from radarr.models.host_config_resource import HostConfigResource as HostConfigResource
from radarr.models.import_list_bulk_resource import ImportListBulkResource as ImportListBulkResource
from radarr.models.import_list_config_resource import ImportListConfigResource as ImportListConfigResource
from radarr.models.import_list_exclusion_bulk_resource import ImportListExclusionBulkResource as ImportListExclusionBulkResource
from radarr.models.import_list_exclusion_resource import ImportListExclusionResource as ImportListExclusionResource
from radarr.models.import_list_exclusion_resource_paging_resource import ImportListExclusionResourcePagingResource as ImportListExclusionResourcePagingResource
from radarr.models.import_list_resource import ImportListResource as ImportListResource
from radarr.models.import_list_type import ImportListType as ImportListType
from radarr.models.import_rejection_resource import ImportRejectionResource as ImportRejectionResource
from radarr.models.indexer_bulk_resource import IndexerBulkResource as IndexerBulkResource
from radarr.models.indexer_config_resource import IndexerConfigResource as IndexerConfigResource
from radarr.models.indexer_flag_resource import IndexerFlagResource as IndexerFlagResource
from radarr.models.indexer_resource import IndexerResource as IndexerResource
from radarr.models.language import Language as Language
from radarr.models.language_resource import LanguageResource as LanguageResource
from radarr.models.localization_language_resource import LocalizationLanguageResource as LocalizationLanguageResource
from radarr.models.log_file_resource import LogFileResource as LogFileResource
from radarr.models.log_resource import LogResource as LogResource
from radarr.models.log_resource_paging_resource import LogResourcePagingResource as LogResourcePagingResource
from radarr.models.manual_import_reprocess_resource import ManualImportReprocessResource as ManualImportReprocessResource
from radarr.models.manual_import_resource import ManualImportResource as ManualImportResource
from radarr.models.media_cover import MediaCover as MediaCover
from radarr.models.media_cover_types import MediaCoverTypes as MediaCoverTypes
from radarr.models.media_info_resource import MediaInfoResource as MediaInfoResource
from radarr.models.media_management_config_resource import MediaManagementConfigResource as MediaManagementConfigResource
from radarr.models.metadata_config_resource import MetadataConfigResource as MetadataConfigResource
from radarr.models.metadata_resource import MetadataResource as MetadataResource
from radarr.models.modifier import Modifier as Modifier
from radarr.models.monitor_types import MonitorTypes as MonitorTypes
from radarr.models.movie_collection_resource import MovieCollectionResource as MovieCollectionResource
from radarr.models.movie_editor_resource import MovieEditorResource as MovieEditorResource
from radarr.models.movie_file_list_resource import MovieFileListResource as MovieFileListResource
from radarr.models.movie_file_resource import MovieFileResource as MovieFileResource
from radarr.models.movie_history_event_type import MovieHistoryEventType as MovieHistoryEventType
from radarr.models.movie_resource import MovieResource as MovieResource
from radarr.models.movie_resource_paging_resource import MovieResourcePagingResource as MovieResourcePagingResource
from radarr.models.movie_runtime_format_type import MovieRuntimeFormatType as MovieRuntimeFormatType
from radarr.models.movie_statistics_resource import MovieStatisticsResource as MovieStatisticsResource
from radarr.models.movie_status_type import MovieStatusType as MovieStatusType
from radarr.models.naming_config_resource import NamingConfigResource as NamingConfigResource
from radarr.models.notification_resource import NotificationResource as NotificationResource
from radarr.models.parse_resource import ParseResource as ParseResource
from radarr.models.parsed_movie_info import ParsedMovieInfo as ParsedMovieInfo
from radarr.models.ping_resource import PingResource as PingResource
from radarr.models.privacy_level import PrivacyLevel as PrivacyLevel
from radarr.models.profile_format_item_resource import ProfileFormatItemResource as ProfileFormatItemResource
from radarr.models.proper_download_types import ProperDownloadTypes as ProperDownloadTypes
from radarr.models.provider_message import ProviderMessage as ProviderMessage
from radarr.models.provider_message_type import ProviderMessageType as ProviderMessageType
from radarr.models.proxy_type import ProxyType as ProxyType
from radarr.models.quality import Quality as Quality
from radarr.models.quality_definition_limits_resource import QualityDefinitionLimitsResource as QualityDefinitionLimitsResource
from radarr.models.quality_definition_resource import QualityDefinitionResource as QualityDefinitionResource
from radarr.models.quality_model import QualityModel as QualityModel
from radarr.models.quality_profile_quality_item_resource import QualityProfileQualityItemResource as QualityProfileQualityItemResource
from radarr.models.quality_profile_resource import QualityProfileResource as QualityProfileResource
from radarr.models.quality_source import QualitySource as QualitySource
from radarr.models.queue_bulk_resource import QueueBulkResource as QueueBulkResource
from radarr.models.queue_resource import QueueResource as QueueResource
from radarr.models.queue_resource_paging_resource import QueueResourcePagingResource as QueueResourcePagingResource
from radarr.models.queue_status import QueueStatus as QueueStatus
from radarr.models.queue_status_resource import QueueStatusResource as QueueStatusResource
from radarr.models.rating_child import RatingChild as RatingChild
from radarr.models.rating_type import RatingType as RatingType
from radarr.models.ratings import Ratings as Ratings
from radarr.models.rejection_type import RejectionType as RejectionType
from radarr.models.release_profile_resource import ReleaseProfileResource as ReleaseProfileResource
from radarr.models.release_resource import ReleaseResource as ReleaseResource
from radarr.models.remote_path_mapping_resource import RemotePathMappingResource as RemotePathMappingResource
from radarr.models.rename_movie_resource import RenameMovieResource as RenameMovieResource
from radarr.models.rescan_after_refresh_type import RescanAfterRefreshType as RescanAfterRefreshType
from radarr.models.revision import Revision as Revision
from radarr.models.root_folder_resource import RootFolderResource as RootFolderResource
from radarr.models.runtime_mode import RuntimeMode as RuntimeMode
from radarr.models.select_option import SelectOption as SelectOption
from radarr.models.sort_direction import SortDirection as SortDirection
from radarr.models.source_type import SourceType as SourceType
from radarr.models.system_resource import SystemResource as SystemResource
from radarr.models.tmdb_country_code import TMDbCountryCode as TMDbCountryCode
from radarr.models.tag_details_resource import TagDetailsResource as TagDetailsResource
from radarr.models.tag_resource import TagResource as TagResource
from radarr.models.task_resource import TaskResource as TaskResource
from radarr.models.tracked_download_state import TrackedDownloadState as TrackedDownloadState
from radarr.models.tracked_download_status import TrackedDownloadStatus as TrackedDownloadStatus
from radarr.models.tracked_download_status_message import TrackedDownloadStatusMessage as TrackedDownloadStatusMessage
from radarr.models.ui_config_resource import UiConfigResource as UiConfigResource
from radarr.models.unmapped_folder import UnmappedFolder as UnmappedFolder
from radarr.models.update_changes import UpdateChanges as UpdateChanges
from radarr.models.update_mechanism import UpdateMechanism as UpdateMechanism
from radarr.models.update_resource import UpdateResource as UpdateResource

""",
            name=__name__,
            doc=__doc__,
        )
    )
